#!/bin/bash
# Universal py2so Enigma2 Script
# يعمل على DreamOS, openATV, openPLi وغيرها

# الألوان للإخراج
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== py2so Enigma2 Universal Script ===${NC}"
echo -e "${YELLOW}هذا السكريبت يحول .py إلى .so مع الحفاظ على التوافق${NC}"

# detection of architecture
ARCH=$(uname -m)
echo -e "${GREEN}معالجة المعمارية: $ARCH${NC}"

# Set compiler based on architecture
case $ARCH in
    aarch64*)
        CC="aarch64-oe-linux-gcc"
        [ ! -f /usr/bin/$CC ] && ln -sf /usr/bin/gcc /usr/bin/$CC
        ;;
    mips* | mipsel*)
        CC="mipsel-oe-linux-gcc"
        [ ! -f /usr/bin/$CC ] && echo -e "${RED}يرجى تثبيت cross-compiler للمips${NC}" && exit 1
        ;;
    arm*)
        CC="arm-oe-linux-gnueabihf-gcc"
        [ ! -f /usr/bin/$CC ] && echo -e "${RED}يرجى تثبيت cross-compiler للarm${NC}" && exit 1
        ;;
    *)
        CC="gcc"
        ;;
esac

# Installation of dependencies
echo -e "${GREEN}تثبيت التبعيات...${NC}"
opkg update > /dev/null 2>&1
opkg install python3-dev python3-modules gcc make cython 2>/dev/null || \
apt-get update && apt-get install -y python3-dev gcc make cython 2>/dev/null

# Ask for plugin directory
echo -e "${YELLOW}ادخل مسار مجلد البلوجين (مطلوب абсолютный):${NC}"
read -r PLUGIN_DIR

[ ! -d "$PLUGIN_DIR" ] && echo -e "${RED}المجلد غير موجود!${NC}" && exit 1

cd "$PLUGIN_DIR"

# Create universal setup.py
cat > setup.py << 'PYEOF'
# -*- coding: utf-8 -*-
import os
import sys
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext

# Directories to protect (exclude enigma2 core files)
directories = ['api', 'core', 'ratings', 'ui', 'plugins']
ext_modules = []

# Walk and find .py files, skip __init__.py and plugin.py
for dir_name in directories:
    if not os.path.isdir(dir_name):
        continue
    for root, dirs, files in os.walk(dir_name):
        for file in files:
            if file.endswith('.py') and file not in ('__init__.py', 'plugin.py'):
                file_path = os.path.join(root, file)
                # Make module name relative to plugin dir
                rel_path = os.path.relpath(file_path, '.')
                module_name = rel_path.replace('.py', '').replace(os.path.sep, '.')
                ext_modules.append(Extension(module_name, [file_path]))

setup(
    name='protection',
    cmdclass={'build_ext': build_ext},
    ext_modules=ext_modules
)
PYEOF

echo -e "${GREEN}جاري البناء...${NC}"
python3 setup.py build_ext --inplace 2>&1

# After build, create protective structure
echo -e "${GREEN}تهيئة ملفات الحماية...${NC}"

# Move original .py to .py.old (backup) and keep .so
find . -name "*.py" ! -name "*.py.old" ! -name "__init__.py" ! -name "plugin.py" -exec cp {} {}.old \; 2>/dev/null

# Remove .c files generated by Cython
find . -name "*.c" -delete 2>/dev/null

# Create __init__.py that tries .so first, then .py
for init_file in $(find . -name "__init__.py" 2>/dev/null); do
    dir=$(dirname "$init_file")
    echo "Creating protective import for $dir"
    cat > tmp_init.py << 'INITEOF'
import os
import sys

# Try to import from .so first
try:
    # Add current directory to path
    sys.path.insert(0, os.path.dirname(__file__))
    
    # Try .so modules
    import importlib.util
    lib_path = os.path.join(os.path.dirname(__file__), '__init__.so')
    if os.path.exists(lib_path):
        spec = importlib.util.spec_from_file_location("init_module", lib_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        print("Loaded from .so successfully")
    else:
        print("No .so found, using regular import")
except Exception as e:
    print(f"Using regular Python import: {e}")
INITEOF
    cp tmp_init.py "$init_file"
done

# Final cleanup
rm -f setup.py

echo -e "${GREEN}✅ العمليةcompleted!${NC}"
echo -e "${YELLOW}تم تحويل الملفات وحماية الكود${NC}"
echo -e "${YELLOW}الملفات الأصلية تم نسخها كـ .py.old للحفاظ على التوافق${NC}"

# Restart enigma2 gracefully
echo -e "${GREEN}إعادة تشغيل enigma2 للقراءة الملفات الجديدة...${NC}"
killall -9 enigma2 2>/dev/null || true
sleep 2
enigma2 &